improve documentation

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -102,53 +102,53 @@ test_ir%: test_ir%.tsc expected_ir%.wav
 test_wav%: test_wav%.tsc input_wav%.wav expected_wav%.wav
 	@echo "Input-output processing test: $<"
 	@$(LIBPATH) $(VALIDATE) $< || (echo "$(<):2: Validation failed"; false)
-	@$(LIBPATH) $(RENDERFILE) -i input_wav$*.wav -d -f 64 -o test_wav$*.wav $< || (echo "$(<):2: Rendering failed"; false)
+	@$(LIBPATH) $(RENDERFILE) -i input_wav$*.wav -f 64 -o test_wav$*.wav $< || (echo "$(<):2: Rendering failed"; false)
 	@$(LIBPATH) $(COMPARE) expected_wav$*.wav test_wav$*.wav $(TOL) $(RMSTOL) || (echo "$(<):2: Output differs"; false)
 	@rm -f test_wav$*.wav
 
 test_snd%: test_snd%.tsc expected_snd%.wav
 	@echo "Generation test: $<"
 	@$(LIBPATH) $(VALIDATE) $< || (echo "$(<):2: Validation failed"; false)
-	@$(LIBPATH) $(RENDERFILE) -i zeros.wav -d -f 64 -o test_snd$*.wav $< || (echo "$(<):2: Rendering failed"; false)
+	@$(LIBPATH) $(RENDERFILE) -i zeros.wav -f 64 -o test_snd$*.wav $< || (echo "$(<):2: Rendering failed"; false)
 	@$(LIBPATH) $(COMPARE) expected_snd$*.wav test_snd$*.wav $(TOL) $(RMSTOL) || (echo "$(<):2: Output differs"; false)
 	@rm -f test_snd$*.wav
 
 test_pos%: test_pos%.tsc expected_pos%.wav
 	@echo "Position test: $<"
 	@$(LIBPATH) RECTYPE=debugpos $(VALIDATE) $< || (echo "$(<):2: Validation failed"; false)
-	@$(LIBPATH) RECTYPE=debugpos $(RENDERFILE) -i zeros.wav -d -f 64 -o test_pos$*.wav $< || (echo "$(<):2: Rendering failed"; false)
+	@$(LIBPATH) RECTYPE=debugpos $(RENDERFILE) -i zeros.wav -f 64 -o test_pos$*.wav $< || (echo "$(<):2: Rendering failed"; false)
 	@$(LIBPATH) $(COMPARE) expected_pos$*.wav test_pos$*.wav 1e-9 1e-9|| (echo "$(<):2: Output differs"; false)
 	@rm -f test_pos$*.wav
 
 test_rec_%: test_rec.tsc
 	@echo "Receiver test: $< ($*)"
-	@$(LIBPATH) RECEIVER=$* $(RENDERFILE) -i zeros.wav -d -f 64 -o test_rec_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
+	@$(LIBPATH) RECEIVER=$* $(RENDERFILE) -i zeros.wav -f 64 -o test_rec_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
 	@rm -f test_rec_$*.wav
 
 test_reclevel_%: test_level.tsc
 	@echo "Receiver level test: $< ($*)"
-	@$(LIBPATH) RECEIVER=$* CHANNELS=8 $(RENDERFILE) -i zeros.wav -d -f 64 -o test_level_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
+	@$(LIBPATH) RECEIVER=$* CHANNELS=8 $(RENDERFILE) -i zeros.wav -f 64 -o test_level_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
 	@$(LIBPATH) $(COMPLEV) 70 test_level_$*.wav $(LEVTHR) || (echo "$(<):2: Level differs (8ch)"; false)
-	@$(LIBPATH) RECEIVER=$* CHANNELS=36 $(RENDERFILE) -i zeros.wav -d -f 64 -o test_level_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
+	@$(LIBPATH) RECEIVER=$* CHANNELS=36 $(RENDERFILE) -i zeros.wav -f 64 -o test_level_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
 	@$(LIBPATH) $(COMPLEV) 70 test_level_$*.wav $(LEVTHR) || (echo "$(<):2: Level differs (36ch)"; false)
 	@rm -f test_level_$*.wav
 
 test_level_%: test_level_%.tsc
 	@echo "Level test: $< ($*)"
 	@$(LIBPATH) $(VALIDATE) $< || (echo "$(<):2: Validation failed"; false)
-	@$(LIBPATH) RECEIVER=$* $(RENDERFILE) -i zeros.wav -d -f 64 -o test_level_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
+	@$(LIBPATH) RECEIVER=$* $(RENDERFILE) -i zeros.wav -f 64 -o test_level_$*.wav $< || (echo "$(<):2: Rendering failed"; false)
 	@$(LIBPATH) $(COMPLEV) 70 test_level_$*.wav $(LEVTHR) || (echo "$(<):2: Level differs"; false)
 	@rm -f test_level_$*.wav
 
 
 test_fail_%: fail_%.tsc
 	@echo "Failure test: $< ($*)"
-	@(! $(LIBPATH) $(RENDERFILE) -i zeros.wav -d -f 64 -o test_fail.wav $< ) || (echo "$(<):2: Did not fail"; false)
+	@(! $(LIBPATH) $(RENDERFILE) -i zeros.wav -f 64 -o test_fail.wav $< ) || (echo "$(<):2: Did not fail"; false)
 	@rm -f test_fail.wav
 
 test_notfail_%: notfail_%.tsc
 	@echo "No failure test: $< ($*)"
-	@$(LIBPATH) $(RENDERFILE) -i zeros.wav -d -f 64 -o test_fail.wav $< || (echo "$(<):2: Failed."; false)
+	@$(LIBPATH) $(RENDERFILE) -i zeros.wav -f 64 -o test_fail.wav $< || (echo "$(<):2: Failed."; false)
 	@rm -f test_fail.wav
 
 
@@ -156,13 +156,13 @@ test_notfail_%: notfail_%.tsc
 
 db_test_wav%: test_wav%.tsc input_wav%.wav expected_wav%.wav
 	$(LIBPATH) $(VALIDATE) $< 
-	echo run -i input_wav$*.wav -d -f 64 -o test_wav$*.wav $< > gdbcmd
+	echo run -i input_wav$*.wav -f 64 -o test_wav$*.wav $< > gdbcmd
 	$(LIBPATH) gdb $(RENDERFILE) -x gdbcmd
 	$(LIBPATH) $(COMPARE) expected_wav$*.wav test_wav$*.wav 2e-8
 	rm -f test_wav$*.wav
 
 db_test_rec_%: test_rec.tsc
-	echo run -i zeros.wav -d -f 64 -o test_rec_$*.wav $< > gdbcmd
+	echo run -i zeros.wav -f 64 -o test_rec_$*.wav $< > gdbcmd
 	$(LIBPATH) RECEIVER=$* gdb $(RENDERIR) -x gdbcmd
 	rm -f test_rec_$*.wav
 
@@ -173,38 +173,38 @@ db_test_ir%: test_ir%.tsc expected_ir%.wav
 	rm -f test_ir$*.wav
 
 db_test_snd%: test_snd%.tsc expected_snd%.wav
-	echo run -i zeros.wav -o test_snd$*.wav -d -f 64 $< > gdbcmd
+	echo run -i zeros.wav -o test_snd$*.wav -f 64 $< > gdbcmd
 	$(LIBPATH) gdb $(RENDERFILE) -x gdbcmd
 	$(LIBPATH) $(COMPARE) expected_snd$*.wav test_snd$*.wav 1e-9 1e-9
 	rm -f test_snd$*.wav
 
 db_test_pos%: test_pos%.tsc expected_pos%.wav
-	echo run -i zeros.wav -o test_pos$*.wav -d -f 64 $< > gdbcmd
+	echo run -i zeros.wav -o test_pos$*.wav -f 64 $< > gdbcmd
 	$(LIBPATH) gdb $(RENDERFILE) -x gdbcmd
 	$(LIBPATH) ../build/compare_posfile expected_pos$*.wav test_pos$*.wav 1e-9 1e-9
 	rm -f test_pos$*.wav
 
 leak_test_snd%: test_snd%.tsc expected_snd%.wav
-	$(LIBPATH) valgrind --leak-check=full $(RENDERFILE) -i zeros.wav -o test_snd$*.wav -d -f 64 $<
+	$(LIBPATH) valgrind --leak-check=full $(RENDERFILE) -i zeros.wav -o test_snd$*.wav -f 64 $<
 	$(LIBPATH) $(COMPARE) expected_snd$*.wav test_snd$*.wav 1e-9 1e-9
 	rm -f test_snd$*.wav
 
 leak_test_pos%: test_pos%.tsc expected_pos%.wav
-	$(LIBPATH) valgrind --leak-check=full $(RENDERIR) -i zeros.wav -o test_pos$*.wav -d -f 64 $<
+	$(LIBPATH) valgrind --leak-check=full $(RENDERIR) -i zeros.wav -o test_pos$*.wav -f 64 $<
 	$(LIBPATH) ../build/compare_posfile expected_pos$*.wav test_pos$*.wav 1e-9
 	rm -f test_pos$*.wav
 
 leak_%: %.tsc
-	$(LIBPATH) valgrind --leak-check=full  --show-leak-kinds=all $(RENDERFILE) -i zeros.wav -o $*.wav -d -f 64 $<
+	$(LIBPATH) valgrind --leak-check=full  --show-leak-kinds=all $(RENDERFILE) -i zeros.wav -o $*.wav -f 64 $<
 
 valgrind_%: %.tsc
-	$(LIBPATH) valgrind  $(RENDERFILE) -i zeros.wav -o $*.wav -d -f 64 $<
+	$(LIBPATH) valgrind  $(RENDERFILE) -i zeros.wav -o $*.wav -f 64 $<
 
 
 all_init: $(patsubst %,init_%,$(TEST_SND:.tsc=))
 
 init_%: %.tsc
-	$(LIBPATH) valgrind --leak-check=no --undef-value-errors=yes --track-origins=yes $(RENDERFILE) -i zeros.wav -o $*.wav -d -f 64 $<
+	$(LIBPATH) valgrind --leak-check=no --undef-value-errors=yes --track-origins=yes $(RENDERFILE) -i zeros.wav -o $*.wav -f 64 $<
 
 clean:
 	rm -f *~ test*.wav gdbcmd
